language: java
jdk:
- openjdk8

branches:
  only:
  - /.*/

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email:
    recipients:
    - nooheat1228@gmail.com

after_success:
- ./gradlew jacocoRootReport coveralls